apiVersion: v1
kind: Service
metadata:
  name: react-app-service #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: react-app
  type: NodePort #Type of the Kubernetes Service
  ports:
  - protocol: TCP
    port: 80 #Service port
    targetPort: 80 #The port for the React.js application container
    nodePort: 32000